config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'stories#index'

  resources :stories

end

app/models/story.rb
class Story < ActiveRecord::Base
	validates :story_title, presence: true
	validates :story_body, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  def index
  	@stories = Story.all
  end

  def show
  	@story = Story.find(params[:id])
  end

  def new
  	@story = Story.new
  end

  def edit
  	@story = Story.find(params[:id])
  end

  def create
  	@story = Story.new(story_params)

  	if @story.save
  		redirect_to root_path
  	else
  		render :new
  	end
  end

  def update
  	@story = Story.find(params[:id])

  	if @story.update(story_params)
  		redirect_to root_path
  	else
  		render :edit
  	end
  end

  def destroy
  	@story = Story.find(params[:id])
  	@story.destroy

  	redirect_to root_path
  end

  private

  def story_params
  	params.require(:story).permit(:story_title, :story_body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SpamV2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div>
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>
</div>

<%= yield %>

</body>
</html>

app/views/stories/_form.html.erb
<%= form_for @story do |f| %>
	<% if @story.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@story.errors.count, "error") %> prohibited this story from being saved: </h2>
			<ul>
				<% @story.errors.full_messages.each do |msg| %>
				<li>
					<%= msg %>
				</li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<%= f.label :story_title %>
	<%= f.text_field :story_title %>
	<br />
	<%= f.label :story_body %>
	<%= f.text_area :story_body %>
	<br />
	<%= f.submit "Save Story!" %>
<% end %>

app/views/stories/edit.html.erb
<div>
	<h1>Update This Story!</h1>
	<%= render 'stories/form' %>
	<%= link_to 'Delete This Story', story_path(@story), method: :delete,  data: {confirm: 'Are You Sure Want to Delete ' + @story.story_title} %>
	<%= link_to 'Main Page', root_path %>
</div>

app/views/stories/index.html.erb
<div>
	<h1>This is our stories</h1>
	<% @stories.each do |story| %>
		<h2><%= link_to story.story_title, story_path(story) %></h2>
		<p><%= truncate story.story_body, length: 150 %></p>
		<h5>Created since <%= time_ago_in_words(story.created_at) %></h5>
	<% end %>
	<%= link_to 'New Story', new_story_path %>
</div>

app/views/stories/new.html.erb
<div>
	<h1>New Story!</h1>
	<%= render 'stories/form' %>
	<%= link_to 'Main Page', root_path %>
</div>

app/views/stories/show.html.erb
<div>
	<h2><%= @story.story_title %></h2>
	<p><%= @story.story_body %></p>
	<%= link_to 'Edit This Story', edit_story_path(@story) %>
</div>